version: '3.8'

services:
  cdp-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-chatbot
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - DEBUG_MODE=False
    restart: unless-stopped
    command: ["python", "src/main.py", "serve"]

  cdp-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdp-scraper
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG_MODE=False
    restart: "no"
    command: ["python", "src/main.py", "scrape"]
    profiles:
      - scraper